export { ReactComponent as BidsLostIcon } from './bidsLost.svg'
export { ReactComponent as BidsWonIcon } from './bidsWon.svg'
export { ReactComponent as TotalBidsIcon } from './totalBids.svg'
export { ReactComponent as IncreaseIcon } from './increase.svg'
export { ReactComponent as DecreaseIcon } from './decrease.svg'
export { ReactComponent as CalendarIcon } from './calendar.svg'
