const text: { [key: string]: string } = {
  specialEdition: 'Special Edition',
  productPage: 'Product Page',
  days: 'Days',
  hours: 'Hours',
  minutes: 'Min ',
  seconds: 'Sec',
  theNextActionWillBeAvailableOn: 'The next auction will be available on',
  launchTime: 'Launch Time',
  viewAuction: 'View Auction',
  countOfCount: '{{value1}} of {{value2}}',
  auctionDetails: 'Auction Details',
  auctionDetailsContent:
    ' Bid to win Limited Edition Brad Pitt NFTscelebrating Pitt’s greatest cinema moments!\n The auction is now open and will run for 48hrs  ending on Saturday (4/2/21) at Ipm ET\n All editions will be sold to the highest bidder, English auction style`\n • Users may place bids across multiple products and editions as soon as the auction begins\n • At the end of the auction, each of the 349 highest  qualifying bids across all editions will, following receipt of payment, promptly receive their commemorative NFT`s in their crypto wallet! All auctions are subject to the auction terms and conditions, a link to which can be found below.',
  howToBuy: 'How to Buy',
  howToBuyContent:
    'The Brad Pitt’s NFT Collection is being offered exclusively on  Satoshi.ART with a public auction that is now open and will end on Saturday, April 2nd at 7pm ET.\n Any bids made in the Last 10 minutes of the auction will extend each edition auction by 10 additional minutes.\n You will need to setup a MetaMask Wallet to participate in the auction. In order to bid you must pay using Ethereum, the auction will not accept credit cards.',
  howToBuyAdditionalContent:
    'To learn more about purchasing NFTs on Satoshi.ART please click <a href="">HERE</a>.  Video instructions detailing how to setup your MetaMask Wallet are available <a href="">HERE</a>. For full auction terms and conditions, please click <a href="">HERE</a>.',
  authenticVerification: 'Authentic Verification',
  authenticVerificationContent:
    ' Each Limited Edition NFT card is marked with a  unique serial number with guaranteed scarcity and  protected ownership guaranteed by the blockchain. On each card you will find the card`s edition number.\n For instance - When you own the Pittfull#1 NFT, you are the only person in the world with this digital collectible!',
  emailAddress: 'Email address',
  subscribe: 'Subscribe',
  'More Satoshi': 'More Satoshi',
  Privacy: 'Privacy',
  Help: 'Help',
  Install: 'Install',
  goBack: 'Go back',
  cnYourWallet: 'Connect your wallet',
  cnWithOneOfProviders: 'Connect with one of available wallet providers or create a new wallet.',
  weDontOwnKeys: 'We do not own your private keys and cannot access your funds without your confirmation.',
  Info: 'Info',
  Owners: 'Owners',
  History: 'History',
  Bids: 'Bids',
  thereIsNoDscr: 'There is no description provided for this collectible',
  highestBidBy: 'Highest bid by',
  buyNow: 'Buy now',
  placeABid: 'Place a bid',
  serviceFeeProgress: 'Service fee {{ fee }}%.',
  owner: 'Owner',
  creator: 'Creator',
  follow: 'Follow',
  unfollow:'Unfollow',
  createCollectible: 'Create collectible',
  chooseSingleIfYouWantYourCollectible:
    'Choose “Single” if you want your collectible to be one of a kind or “Multiple” if you want to sell one collectible multiple times',
  createCollectibleAdditionalInfo:
    'We do not own your private keys and cannot access your funds without your confirmation.',
  single: 'Single',
  multiple: 'Multiple',
  create: 'Create',
  clearAll: 'Clear all',
  resultsCnt: ' {{ cnt }} results',
  allItems: 'All items',
  sortBy: 'Sort by',
  dashboard: 'Dashboard',
  orderList: 'Order List',
  disconnect: 'Disconnect',
  hello: 'Hello',
  searchHere: 'Search here',
  first: 'First',
  last: 'Last',
  today: 'Today',
  lastWeek: 'Last week',
  lastMonth: 'Last month',
  lastYear: 'Last year',
  allEvents: 'All events',
  bid: 'Bid',
  buy: 'Buy',
  sell: 'Sell',
  showingCountOfData: 'Showing {{ count }} from {{ total }} data',
  orderId: 'Order ID',
  event: 'Event',
  cost: 'Cost',
  artName: 'Art name',
  artist: 'Artist',
  Followers: 'Followers',
  Following: 'Following',
  date: 'Date',
  close: 'Close',
  youAreAboutToPlaceABidFor: 'You are about to place a bid for <1>{{name}}</1>  by <1>{{author}}</1>',
  youAreAboutToPurchase: 'You are about to purchase',
  proceedToPayment: 'Proceed to payment',
  by: 'by',
  becomeArtist: 'Become an artist',
  yourBid: 'Your bid',
  enterQuantity: 'Enter quantity',
  countAvailable: ' {{count}} available',
  yourBalance: 'Your balance',
  serviceFee: 'Service fee',
  totalBidAmount: 'Total bid amount',
  cancel: 'Cancel',
  checkout: 'Checkout',
  howItWorks: 'How it works',
  community: 'Community',
  dropOfTheDay: 'Drop of the Day',
  seeAll: 'See All',
  allThe: 'All the',
  inTheWorldNowTogetherHereForYou: 'in the world, now together. Here for you.',
  exploreCollections: 'Explore collections',
  seeAllHistory: 'See all History',
  previousWeeklyIterations: 'Previous Weekly Iterations',
  takeTimeToAppreciateTheArtWork: 'Take time to appreciate the artwork,',
  youWillBeAbleToBuyItSoon: "You'll be able to buy it soon!",
  recentlyCollected: 'Recently Collected',
  topArtists: 'Top Artists',
  recentSales: 'Recent Sales',
  topCollectors: 'Top Collectors',
  artworksOwned: 'Artworks Owned',
  largestCollections: 'Largest Collections',
  topSellers: 'Top Sellers',
  topBuyers: 'Top Buyers',
  wrongNetwork: 'Wrong Network',
  wrongNetworkMsg: 'Switch to Mainnet',
  termsOfServiceDomain: 'Satoshi.Art Terms of Service',
  termsOfServiceDomainInfo:
    'Please take a few minutes to read and understand <1>Satoshi.Art</1> Terms of Service. To continue, you’ll need to accept the Terms of Service by checking the box.',
  atLeast13YearOld: 'I am at least 13 years old',
  acceptTermsOfService: 'I accept the Satoshi.Art terms of service',
  goToDownloadPage: 'Go to Download Page',
  uploadFile: 'Upload file',
  chooseFile: 'Choose file',
  uploadCover: 'Upload cover',
  putOnSale: 'Put on sale',
  youWillReceiveBids: 'You’ll receive bids on this item',
  instantSalePrice: 'Instant sale price',
  enterThePriceForInstantlySold: 'Enter the price for which the item will be instantly sold',
  youWillReceiveCnt: 'You will receive {{ count }} {{ currency }} $ {{ amount }}',
  unlockOncePurchased: 'Unlock once purchased',
  unlockOncePurchasedContent: 'Content will be unlocked after successful transaction',
  markdownIsSupported: 'Tip: Markdown syntax is supported',
  chooseCollection: 'Choose collection',
  name: 'Name',
  description: 'Description',
  withPreservedLineBreaks: 'With preserved line-breaks',
  royalties: 'Royalties',
  suggestedPercentages: 'Suggested: {{value1}}%',
  numberOfCopies: 'Number of copies',
  amountOfTokens: 'Amount of tokens',
  propertiesOptional: 'Properties <1>(Optional)</1>',
  createItem: 'Create Item',
  unsavedChanges: 'Unsaved changes',
  noBidsYet: 'No bids yet',
  previewOfYourNewCollectible: 'Preview of your new collectible',
  searchByCreatorCollectibleOrCollection: 'Search by creator, collectible or collection',
  backToHomePage: 'Back to homepage',
  search: 'Search',
  submitARequest: 'Submit a Request',
  yourEmailAddress: 'Your Email Address',
  fieldIsRequired: 'Field is required',
  whatDoYouNeedToHelpWith: 'What do you need help with?',
  pleaseSelectYourIssueAbove: 'Please select your issue above',
  pleaseProvideAOneLineDescriptionIssue: 'Please provide a one-line description of the issue you`re currently facing.',
  yourAddress: 'Your Address',
  pleaseDescribeTheProblemInAsMuchDetailAs: 'Please describe the problem in as much detail as possible.',
  descriptionOptional: 'Description <1>(Optional)<1>',
  attachmentsOptional: 'Attachments (optional)',
  addOrDropFilesHere: 'Add or drop files here',
  submit: 'Submit',
  brokenImageOrVideo: 'Broken Image/Video',
  itemNotDisplayed: 'Item Not Displayed',
  other: 'Other',
  questionOrComment: 'Question/Comment',
  securityVulnerability: 'Security Vulnerability',
  verificationIssueOrQuestion: 'Verification Issue/Question',
  'privacy-domainPrivacy': 'Satoshi.Art Privacy',
  'privacy-privacyLastUpdated': 'Last Updated: {{month}} {{date}}',
  'privacy-p1':
    'Our Platform was built with your privacy in mind. This Privacy Policy (“<1>Policy</1>”) describes how we at Pixura collect, use, share, and secure your Personal Information when you visit the SuperRare Platform ([https://superrare.co](https://superrare.co/), [https://superrare.com](https://superrare.com/)) (the “<1>Platform</1>”) or create, buy, transfer, or trade unique SuperRare Items in our Market (the “<1>Market</1>”).',
  'privacy-p2':
    'By accessing the Site or trading SuperRare Items through the Market, you agree to this Privacy Policy and our Terms of Use.',
  'privacy-p3':
    'We may collect information reasonably capable of identifying you as an individual (“**Personal Information**”). Personal Information does not include anonymous or aggregate information that does not identify you as an individual.',
  'privacy-p4':
    '<1>Creating a User Account:</1> If you sign up to use our Platform, we collect your Ethereum wallet address, username, and email address. The User may elect to provide their full name, location, biographical information, and a website.',
  'privacy-p5':
    '<1>Applying as an Artist:</1> If you want to join the world’s top digital artists in our Market, we collect your first and last name, email address, a short application video, Ethereum wallet address, and information about your art.',
  'privacy-p6':
    '<1>Visiting the Site or Market:</1> We also collect basic analytics data when you access or use the Platform through Cookies. See our Cookies Policy below for more information about the Cookies we use and what data they may collect.',
  'privacy-p7': 'We use the Personal Information we collect to:',
  'privacy-p8':
    'We rely on service providers to make some of the Platform’s features work, including our website providers or the company who supports the chat feature. These providers may have access to Personal Information we collect so they can do this work on our behalf. We work hard to ensure these providers only access and use your information as necessary to perform their functions.',
  'privacy-p9':
    'We also collect basic analytics data through Cookies when you access or use the Platform. A “**Cookie** is a small piece of data or text file stored on the local hard disk of your computer or mobile device. These include our own first-party Cookies and third-party Cookies. Some Cookies are only stored temporarily and destroyed each time you close your web browser. Others may remain on your browser and may collect and store data for a period of time after you have left the Platform.',
  'privacy-p10':
    '<1>Functionality:</1>Our Platform uses Cookies to ensure the Platform functions properly, including page loads or our chat feature.',
  'privacy-p11':
    '<1>Performance and Analytics:</1> Our Platform uses Cookies to gather usage and performance data. This enables us to monitor and improve the Platform’s performance, our services, and your experience.',
  'privacy-p12':
    '<1>Google Analytics</1> We use Google Analytics to understand how users interact with the Platform and serve you information about products or services we think you may like. You can find out more about Google Analytics and how to opt-out **here**.',
  'privacy-p13':
    'If you wish to prevent Cookies from tracking your activity on our Platform or visits across multiple websites, you can set your browser to block certain Cookies or notify you when a Cookie is set. For more information on how you can customize your browser’s Cookie setting please visit the link to your web browser below:',
  'privacy-p14':
    'You may opt-out of interest-based advertising in general by visiting the Digital Advertising Alliance’s or Network Advertising Initiative’s websites. We are not responsible for the completeness, effectiveness, or accuracy of any third-party opt-out options or programs.',
  'privacy-p15':
    'If you block Cookies, some features that make the Platform function property may not work and your experience may be affected.',
  'privacy-p16':
    'You may contact us at [hello@superrare.com] to update or correct any Personal Information we collected about you.',
  'privacy-p17':
    'You can unsubscribe from commercial or marketing communications from us by contacting us at [hello@superrare.com](mailto:hello@superrare.com) or following the instructions at the bottom of any email you receive from us.',
  'privacy-p18':
    '<1>Third-party marketing:</1> We do not provide your information to third parties for their direct marketing purposes. However, we may share aggregate or other information that no longer personally identifies you with other parties for our business purposes, marketing, analytics, or other uses.',
  'privacy-p19':
    '<1>Do not track:</1>Some web browsers or smartphones can set “Do Not Track” requests to block user activity from being tracked across web pages or devices. We do not honor Do Not Track mechanism as there is no industry-standard  way to do so.',
  'privacy-p20':
    'The Platform is not intended for use by children under the age of 18, and we do not knowingly collect Personal Information from children under the age of 13. If we learn we collected Personal Information from a child under 13 we will delete that information from our files.',
  'privacy-list1-item1': 'Make the Platform work and enable you to list, buy, transfer, or trade unique digital art;',
  'privacy-list1-Item2': 'Provide you with critical updates, confirmations, or security alerts;',
  'privacy-list1-item3': 'Provide support or respond to your comments or questions;',
  'privacy-list1-item4': 'Personalize and improve your experience;',
  'privacy-list1-item5':
    'Inform you about products, services, news, or promotional opportunities we think might interest you;',
  'privacy-list1-item6': 'Analyze and improve our Platform.',
  connectWallet: 'Connect Wallet',
  proceedAnyway: 'Proceed Anyway',
  thisPageIsBestViewedWithDesktopDevices: 'This page is best viewed with desktop devices',
  'hello!': 'Hello!',
  's-art-intro1': 'The future is NOW!',
  's-art-intro2': 'By artists and For artists.',
  's-art-intro3': 'Together, we will be non-stoppable.',
  's-art-p1':
    'Satoshi.Art is the brainchild of a diverse and talented group of people from both worlds of art and finance. As a team of passionate entrepreneurs and world-renowned musicians, we have come together with one goal in mind: to ensure that artists receive the recognition they deserve for their creativity.',
  's-art-p2':
    'To achieve this goal, Satoshi.Art provides the platform where artists from around the world can collaborate and showcase their artwork in a digital form that is both unique and unreplaceable, allowing fans to enjoy exclusive ownership. ',
  's-art-p3':
    'There are, of course, other platforms that allow people to buy and sell NFTs. What sets Satoshi.Art apart from all of them is not just the fact artists are behind Satoshi.Art, who best understand the concerns and grievances of fellow artists. It is also unprecedented types of services that we provide on our platform, including the environment we create, for example, for an American artist to collaborate with an artist from China in a way that will increase the volume of potential interest in their digital artwork. Satoshi.Art is truly a platform by artists and for artists.',
  's-art-p4': 'Satoshi.Art is 100% minority owned and firmly embraces workplace diversity and equality.',
  proceed: 'Proceed',
  yourTokenIsBeingMinted: 'Your token is being minted',
  miningProgressModalContent:
    " It won't appear on our site until the transaction is\nsuccessfully completed. This might take minutes or even\nhours. To monitor status of this transaction head to:",
  oopsSomethingWentWrong: 'Oops, something went wrong',
  pleaseTryConnectYourWalletManually: 'Please try to connect your wallet manually via MetaMask extension.',
  tryAgain: 'Try again',
  youHaveClosedMetamask: 'You’ve closed MetaMask',
  hiWelcomeBackToDashboard: 'Hi, {{name}}. Welcome back to your dashboard.',
  filterPeriod: 'Filter Period',
  done: 'Done',
  followingBtn: 'Following',
  viewAll: 'View All',
  following: 'Following',
  followers: 'Followers',
  chart: 'Chart',
  showValue: 'Show Value',
  pieChart: 'Pie Chart',
  totalOrder: 'Total\nOrder',
  customerGrowth: 'Customer\nGrowth',
  totalRevenue: 'Total Revenue',
  bidHistory: 'Bid History',
  bidsWon: 'Bids Won',
  totalBids: 'Total Bids',
  bidsLost: 'Bids Lost',
  daysCountInBrackets: '({{count}} days)',
  viewBid: 'View Bid',
  editBid: 'Edit Bid',
  cancelBid: 'Cancel Bid',
  yourLatestBids: 'Your Latest Bids',
  onSale: 'On Sale',
  changePrice: 'Change price',
  removeFromSale: 'Remove from sale',
  transferToken: 'Transfer token',
  burnToken: 'Burn token',
  created: 'Created',
  setAPrice: 'Set a price',
  collections: 'Collections',
  myItems: 'My Items',
  editProfile: 'Edit Profile',
  editCelebrityProfile: 'Edit Celebrity Profile',
  putOnSaleBtn: 'Put on Sale',
  putOnAuctionBtn: 'Put on Auction',
  changePriceBtn: 'Change Price',
  removeFromSaleBtn: 'Remove from Sale',
  recentlyAdded: 'Recently added',
  tokensLoadingFailed: 'Loading tokens was failed',
  putOnSaleServiceFee: 'Service fee: <b>{{fee}}%</b>',
  putOnSaleReceiveAmount: 'You will receive <b>{{ count }} {{ currency }}</b> $ {{ amount }}',
  nextStep: 'Next step',
  requestToBecomeArtist:'Request To Become Artist'
 
};

export default text;
